name: MacOS

on:
  push:
    branches:
      - dev
      - CI
  workflow_dispatch:
    inputs:
      build_config:
        description: 'Comma-separated "Release" and/or "Debug"'
        default: '"Release", "Debug"'
        required: true

jobs:
  macos_clang:
    name: MacOS | Clang
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        build_config: ${{ fromJSON(format('[{0}]', inputs.build_config || '"Release", "Debug"')) }}
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Build CppLogger
        uses: lukka/run-cmake@v10
        with:
          # This is the name of the CMakePresets.json's configuration to use to generate
          # the project files.
          configurePreset: "Clang"
          
          # This is the name of the CMakePresets.json's configuration to build the project.
          buildPreset: "Clang ${{ matrix.build_config }}"
      
      - name: Runtime test Direct Build
        uses: threeal/ctest-action@v1.0.0
        with:
          test-dir: out/build/Clang/src/Tests/DirectBuild
          build-config: ${{ matrix.build_config }}
        
      - name: Runtime test Build with Link to Shared Lib
        uses: threeal/ctest-action@v1.0.0
        with:
          test-dir: out/build/Clang/src/Tests/SharedLibLink
          build-config: ${{ matrix.build_config }}